using System.Collections.Generic;

namespace Horizon.PackageEditors.Gears_of_War_Judgment.Profile
{
    class ProfileSettings : GearSettings
    {
        internal ProfileSettings(byte[] encryptionKey, byte[] data, ulong onlineXuid, bool secured)
            : base(encryptionKey, data, onlineXuid, secured, StringMap)
        {

        }

        protected override void IncrementSync()
        {
            this["ProfileUploaded"] = 0;
        }

        private static readonly Dictionary<string, int> StringMap = new Dictionary<string, int>
        {
            { "ControllerVibration", 1 },
            { "InvertY", 2 },
            { "VoiceViaSpeakers", 6 },
            { "VoiceVolume", 7 },
            { "DifficultyLevel", 12 },
            { "ControllerSensitivity", 13 },
            { "FirstPreferredColor", 14 },
            { "SecondPreferredColor", 15 },
            { "AutoAim", 16 },
            { "AutoCenter", 17 },
            { "MovementControl", 18 },
            { "TransmissionPreference", 19 },
            { "RaceCameraPreference", 20 },
            { "BrakePreference", 21 },
            { "AcceleratorPreference", 22 },
            { "Version", 26 },
            { "HUD", 36 },
            { "MatureLanguage", 37 },
            { "Subtitles", 40 },
            { "Gore", 46 },
            { "MusicVolume", 41 },
            { "FXVolume", 42 },
            { "DialogueVolume", 43 },
            { "StickConfiguration", 38 },
            { "TriggerConfiguration", 39 },
            { "PreferredCOGCharacter", 44 },
            { "PreferredLocustCharacter", 45 },
            { "GameIntensity", 47 },
            { "PictogramTooltips", 48 },
            { "GammaSetting", 49 },
            { "DefaultMPWeapon", 50 },
            { "ControlScheme", 51 },
            { "TelevisionType", 53 },
            { "VersusGameType", 100 },
            { "VersusMatchMode", 101 },
            { "VersusPartyType", 102 },
            { "VersusSelectedMap", 103 },
            { "MPFriendlyFire", 120 },
            { "MPRoundTime", 121 },
            { "MPBleedout", 122 },
            { "MPWeaponSwap", 123 },
            { "MPRoundsToWin", 124 },
            { "MPBotDiff", 125 },
            { "NewbieRoundScore", 186 },
            { "KOTHRoundScore", 206 },
            { "WingmanScore", 247 },
            { "HordeEnemyDiff", 266 },
            { "SPTutorials1", 54 },
            { "SPTutorials2", 55 },
            { "MPTutorials1", 56 },
            { "MPTutorials2", 57 },
            { "TurnInverion", 58 },
            { "TargetSensitivity", 59 },
            { "ZoomSensitivity", 60 },
            { "MPNumBots", 126 },
            { "HordeWave", 267 },
            { "DiscoverFound1", 61 },
            { "DiscoverFound2", 62 },
            { "DiscoverNeedsViewed1", 63 },
            { "DiscoverNeedsViewed2", 64 },
            { "MapSelectionMode", 65 },
            { "WeapSwap_NadeLauncher", 280 },
            { "WeapSwap_Vulcan", 281 },
            { "WeapSwap_Boomshot", 282 },
            { "WeapSwap_Flame", 283 },
            { "WeapSwap_Sniper", 284 },
            { "WeapSwap_Bow", 285 },
            { "WeapSwap_Mulcher", 286 },
            { "WeapSwap_Mortar", 287 },
            { "WeapSwap_HOD", 288 },
            { "WeapSwap_Breechshot", 289 },
            { "MercyRules", 467 },
            { "CompletedChaptersCasual1", 66 },
            { "CompletedChaptersCasual2", 67 },
            { "CompletedChaptersNormal1", 68 },
            { "CompletedChaptersNormal2", 69 },
            { "CompletedChaptersHard1", 70 },
            { "CompletedChaptersHard2", 71 },
            { "CompletedChaptersInsane1", 72 },
            { "CompletedChaptersInsane2", 73 },
            { "CompletedChaptersArcadeCasual1", 74 },
            { "CompletedChaptersArcadeCasual2", 75 },
            { "CompletedChaptersArcadeNormal1", 76 },
            { "CompletedChaptersArcadeNormal2", 77 },
            { "CompletedChaptersArcadeHard1", 78 },
            { "CompletedChaptersArcadeHard2", 79 },
            { "CompletedChaptersArcadeInsane1", 80 },
            { "CompletedChaptersArcadeInsane2", 81 },
            { "UnlockedUnlockables", 82 },
            { "UnlockableNeedsViewed", 83 },
            { "CoopInviteType", 84 },
            { "CampCheckpointUsage", 85 },
            { "LastCheckpointSlot", 86 },
            { "CoopCompletedChapters1", 87 },
            { "CoopCompletedChapters2", 88 },
            { "MPMapsCompleted", 89 },
            { "NumEnemiesKilled", 90 },
            { "PlaylistId", 91 },
            { "PlayerSkill", 93 },
            { "ProfileUploaded", 300 },
            { "CampaignMode", 104 },
            { "HordeWavesBeatEasy1", 315 },
            { "HordeWavesBeatEasy2", 316 },
            { "UnlockedChapterAccess1", 95 },
            { "UnlockedChapterAccess2", 96 },
            { "WeapTutorialsOn", 97 },
            { "WeapSwap_Shield", 295 },
            { "SPTutorials3", 330 },
            { "MPTutorials3", 331 },
            { "TrainTutorials1", 332 },
            { "TrainTutorials2", 333 },
            { "TrainTutorials3", 334 },
            { "CompletedAchievementMask1", 140 },
            { "CompletedAchievementMask2", 141 },
            { "UnviewedAchievementMask1", 142 },
            { "UnviewedAchievementMask2", 143 },
            { "SelectedMedal", 98 },
            { "AccessedMPPrefs", 99 },
            { "DefaultSecondaryMPWeapon", 130 },
            { "SPTutorials4", 335 },
            { "MPTutorials4", 336 },
            { "TrainTutorials4", 337 },
            { "BandwidthTestTimestamp", 338 },
            { "UpstreamBandwidth1", 339 },
            { "UpstreamBandwidth2", 340 },
            { "UpstreamBandwidth3", 341 },
            { "UpstreamBandwidth4", 342 },
            { "UpstreamBandwidth5", 343 },
            { "BandwidthHistorySize", 344 },
            { "GoodHostRatio", 345 },
            { "PlaylistIdRanked", 92 },
            { "StandByDemerits", 350 },
            { "QuitDemerits", 351 },
            { "HordeWavesBeatNormal1", 317 },
            { "HordeWavesBeatNormal2", 318 },
            { "HordeWavesBeatHard1", 319 },
            { "HordeWavesBeatHard2", 320 },
            { "WeaponSkin_Lancer", 106 },
            { "WeaponSkin_Hammerburst", 107 },
            { "WeaponSkin_Retro", 108 },
            { "WeaponSkin_Gnasher", 109 },
            { "WeaponSkin_SawedOff", 110 },
            { "IsBanned", 364 },
            { "bIsEpicDev", 365 },
            { "SiegeEnemyDiff", 268 },
            { "SiegeWave", 269 },
            { "RecentDiscover1", 370 },
            { "RecentDiscover2", 371 },
            { "RecentDiscover3", 372 },
            { "RecentDiscover4", 373 },
            { "RecentDiscover5", 374 },
            { "OmniDirEvade", 375 },
            { "RecentChallenge1", 376 },
            { "RecentChallenge2", 377 },
            { "RecentChallenge3", 378 },
            { "RecentChallenge4", 379 },
            { "RecentChallenge5", 380 },
            { "TDMKills", 310 },
            { "MatchTypesPlayedBitmask", 311 },
            { "ExecutionTypesBitmask", 312 },
            { "BeastKillsBitmask", 327 },
            { "FullCoopCompletedChapters1", 313 },
            { "FullCoopCompletedChapters2", 314 },
            { "HasRookieGear", 383 },
            { "HasVeteranGear", 384 },
            { "HasEnumedCheevos", 385 },
            { "HasHoardTheHorde", 386 },
            { "HasGearsPCCheevo", 392 },
            { "HasGears1Camp", 389 },
            { "HasGears2Camp", 387 },
            { "HasGears3Camp", 393 },
            { "ConfiguredVideoSettings", 395 },
            { "DisconnectCount", 394 },
            { "bIsRiftDev", 366 },
            { "HasControllerSensitivityBeenRead", 367 },
            { "GearControllerSensitivity", 368 },
            { "CTLCaptureTime", 226 },
            { "LastCalendarVersion", 396 },
            { "MPWeaponRespawn", 127 },
            { "HordeWavesBeatInsane1", 321 },
            { "HordeWavesBeatInsane2", 322 },
            { "SiegeWavesBeatEasy", 323 },
            { "SiegeWavesBeatNormal", 324 },
            { "SiegeWavesBeatHard", 325 },
            { "SiegeWavesBeatInsane", 326 },
            { "SelectedTitle", 111 },
            { "LastDataCenterId", 397 },
            { "RecModeGraduate", 398 },
            { "SplitScreenCount", 399 },
            { "MpMatchesPlayed", 400 },
            { "RecModeMatchesPlayed", 401 },
            { "RecModeTotalXp", 402 },
            { "WeapSwap_IncendiaryGrenade", 292 },
            { "WeapSwap_HeavySniper", 293 },
            { "WeapSwap_DiggerLauncher", 294 },
            { "WantMutators", 128 },
            { "Depth3dEnabled", 112 },
            { "Depth3dSetting", 113 },
            { "HasGearStickConfigBeenRead", 405 },
            { "EmsRequests", 406 },
            { "EmsErrors", 407 },
            { "HasSeenRecapMovie", 408 },
            { "ArcadeChaptersPlayed", 309 },
            { "DLCBangBitfield", 409 },
            { "MoraleBoostsCompletedCasual1", 410 },
            { "MoraleBoostsStarted", 411 },
            { "CompletedChaptersCasual3", 412 },
            { "CompletedChaptersNormal3", 413 },
            { "CompletedChaptersHard3", 414 },
            { "CompletedChaptersInsane3", 415 },
            { "CompletedChaptersArcadeCasual3", 416 },
            { "CompletedChaptersArcadeNormal3", 417 },
            { "CompletedChaptersArcadeHard3", 418 },
            { "CompletedChaptersArcadeInsane3", 419 },
            { "CoopCompletedChapters3", 420 },
            { "UnlockedChapterAccess3", 421 },
            { "FullCoopCompletedChapters3", 422 },
            { "MoraleBoostsCompletedCasual2", 423 },
            { "MoraleBoostsStarted2", 424 },
            { "PrestigeMessaged", 425 },
            { "FFARoundScore", 426 },
            { "ChaptersScore", 427 },
            { "MoraleBoostsCompletedInsane1", 428 },
            { "MoraleBoostsCompletedInsane2", 429 },
            { "HumanClassKillsBitmask", 328 },
            { "WeaponSkin_HammerburstRetro", 431 },
            { "WeaponSkin_Marksman", 430 },
            { "PawnShader_BairdJack", 432 },
            { "PawnShader_ColeJack", 433 },
            { "PawnShader_SofiaJack", 434 },
            { "PawnShader_GarronJack", 435 },
            { "PawnShader_YoungMarcus", 436 },
            { "PawnShader_YoungDom", 437 },
            { "PawnShader_Loomis", 438 },
            { "PawnShader_MaleOnyx", 439 },
            { "PawnShader_FemaleOnyx", 440 },
            { "PawnShader_Anya", 441 },
            { "PawnShader_Baird", 442 },
            { "PawnShader_Cole", 443 },
            { "PawnShader_Paduk", 444 },
            { "PawnShader_Minh", 445 },
            { "PawnShader_Tai", 446 },
            { "PawnShader_Trishka", 447 },
            { "PawnShader_Grayson", 448 },
            { "GameTutorialsOn", 114 },
            { "ShouldShowEpilogueBang", 449 },
            { "NormalPrizeBoxCount", 450 },
            { "RarePrizeBoxCount", 451 },
            { "EpicPrizeBoxCount", 452 },
            { "MapsCompletedFFA", 460 },
            { "MapsCompletedHvB", 461 },
            { "MapsCompletedTDM", 462 },
            { "MapsCompletedDOM", 463 },
            { "MapsCompletedSUR", 464 },
            { "TDMRoundsWon", 465 },
            { "HvBMatchesWon", 466 },
            { "SawNewToGearsScreen", 115 },
            { "PawnShader_AlexBrand", 453 },
            { "PawnShader_JungleTai", 454 },
            { "WeaponSkin_NadeLauncher", 105 },
            { "MoraleBoostsCompletedHardcore1", 468 },
            { "MoraleBoostsCompletedHardcore2", 469 },
            { "MoraleBoostsCompletedNormal1", 470 },
            { "MoraleBoostsCompletedNormal2", 471 },
            { "FirstEpicPointsPurchase", 116 },
            { "SPTutorials5", 346 },
            { "MPTutorials5", 347 },
            { "TrainTutorials5", 348 },
            { "NewNormalPrizeBox", 472 },
            { "NewRarePrizeBox", 473 },
            { "NewEpicPrizeBox", 474 },
            { "AnlPresentDLCMask1", 475 },
            { "AnlPresentDLCMask2", 476 },
            { "AnlPresentDLCMask3", 477 },
            { "AnlPresentDLCMask4", 478 },
            { "FinishedOnScorecard", 481 },
            { "InventorySnapOnScorecard1", 482 },
            { "InventorySnapOnScorecard2", 483 },
            { "InventorySnapOnScorecard3", 484 }
        };

        /*private static readonly Dictionary<int, Map> Defaults = new Dictionary<int, Map>
        {
            { 1, new Map { Owner = OnlineProfilePropertyOwner.OnlineService, ID = 1, DataType = SettingsDataType.Int32, Value = 3 } },
            { 2, new Map { Owner = OnlineProfilePropertyOwner.OnlineService, ID = 2, DataType = SettingsDataType.Int32, Value = 0 } },
            { 13, new Map { Owner = OnlineProfilePropertyOwner.OnlineService, ID = 13, DataType = SettingsDataType.Int32, Value = 0 } },
            { 18, new Map { Owner = OnlineProfilePropertyOwner.OnlineService, ID = 18, DataType = SettingsDataType.Int32, Value = 0 } },
            { 35, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 35, DataType = SettingsDataType.Int32, Value = 0 } },
            { 36, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 36, DataType = SettingsDataType.Int32, Value = 0 } },
            { 37, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 37, DataType = SettingsDataType.Int32, Value = 0 } },
            { 38, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 38, DataType = SettingsDataType.Int32, Value = 0 } },
            { 39, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 39, DataType = SettingsDataType.Int32, Value = 0 } },
            { 40, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 40, DataType = SettingsDataType.Int32, Value = 0 } },
            { 41, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 41, DataType = SettingsDataType.Float, Value = 1060320051 } },
            { 42, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 42, DataType = SettingsDataType.Float, Value = 1060320051 } },
            { 43, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 43, DataType = SettingsDataType.Float, Value = 1060320051 } },
            { 44, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 44, DataType = SettingsDataType.Int32, Value = 0 } },
            { 45, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 45, DataType = SettingsDataType.Int32, Value = 0 } },
            { 46, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 46, DataType = SettingsDataType.Int32, Value = 0 } },
            { 47, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 47, DataType = SettingsDataType.Int32, Value = 1 } },
            { 48, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 48, DataType = SettingsDataType.Int32, Value = 0 } },
            { 49, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 49, DataType = SettingsDataType.Float, Value = 1074580685 } },
            { 50, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 50, DataType = SettingsDataType.Int32, Value = 13 } },
            { 51, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 51, DataType = SettingsDataType.Int32, Value = 0 } },
            { 53, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 53, DataType = SettingsDataType.Int32, Value = 0 } },
            { 100, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 100, DataType = SettingsDataType.Int32, Value = 0 } },
            { 101, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 101, DataType = SettingsDataType.Int32, Value = 1 } },
            { 102, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 102, DataType = SettingsDataType.Int32, Value = 1 } },
            { 103, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 103, DataType = SettingsDataType.Int32, Value = 0 } },
            { 120, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 120, DataType = SettingsDataType.Int32, Value = 0 } },
            { 121, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 121, DataType = SettingsDataType.Int32, Value = 4 } },
            { 122, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 122, DataType = SettingsDataType.Int32, Value = 2 } },
            { 123, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 123, DataType = SettingsDataType.Int32, Value = 0 } },
            { 124, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 124, DataType = SettingsDataType.Int32, Value = 0 } },
            { 125, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 125, DataType = SettingsDataType.Int32, Value = 0 } },
            { 186, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 186, DataType = SettingsDataType.Int32, Value = 8 } },
            { 206, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 206, DataType = SettingsDataType.Int32, Value = 8 } },
            { 247, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 247, DataType = SettingsDataType.Int32, Value = 1 } },
            { 266, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 266, DataType = SettingsDataType.Int32, Value = 1 } },
            { 54, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 54, DataType = SettingsDataType.Int32, Value = 0 } },
            { 55, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 55, DataType = SettingsDataType.Int32, Value = 0 } },
            { 56, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 56, DataType = SettingsDataType.Int32, Value = 0 } },
            { 57, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 57, DataType = SettingsDataType.Int32, Value = 0 } },
            { 58, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 58, DataType = SettingsDataType.Int32, Value = 0 } },
            { 59, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 59, DataType = SettingsDataType.Float, Value = 1061997773 } },
            { 60, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 60, DataType = SettingsDataType.Float, Value = 1061997773 } },
            { 126, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 126, DataType = SettingsDataType.Int32, Value = 9 } },
            { 267, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 267, DataType = SettingsDataType.Int32, Value = 0 } },
            { 61, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 61, DataType = SettingsDataType.Int32, Value = 0 } },
            { 62, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 62, DataType = SettingsDataType.Int32, Value = 0 } },
            { 63, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 63, DataType = SettingsDataType.Int32, Value = 0 } },
            { 64, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 64, DataType = SettingsDataType.Int32, Value = 0 } },
            { 65, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 65, DataType = SettingsDataType.Int32, Value = 1 } },
            { 280, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 280, DataType = SettingsDataType.Int32, Value = 12 } },
            { 281, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 281, DataType = SettingsDataType.Int32, Value = 11 } },
            { 282, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 282, DataType = SettingsDataType.Int32, Value = 4 } },
            { 283, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 283, DataType = SettingsDataType.Int32, Value = 9 } },
            { 284, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 284, DataType = SettingsDataType.Int32, Value = 6 } },
            { 285, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 285, DataType = SettingsDataType.Int32, Value = 7 } },
            { 286, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 286, DataType = SettingsDataType.Int32, Value = 2 } },
            { 287, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 287, DataType = SettingsDataType.Int32, Value = 1 } },
            { 288, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 288, DataType = SettingsDataType.Int32, Value = 8 } },
            { 289, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 289, DataType = SettingsDataType.Int32, Value = 13 } },
            { 467, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 467, DataType = SettingsDataType.Int32, Value = 1 } },
            { 66, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 66, DataType = SettingsDataType.Int32, Value = 0 } },
            { 67, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 67, DataType = SettingsDataType.Int32, Value = 0 } },
            { 68, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 68, DataType = SettingsDataType.Int32, Value = 0 } },
            { 69, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 69, DataType = SettingsDataType.Int32, Value = 0 } },
            { 70, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 70, DataType = SettingsDataType.Int32, Value = 0 } },
            { 71, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 71, DataType = SettingsDataType.Int32, Value = 0 } },
            { 72, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 72, DataType = SettingsDataType.Int32, Value = 0 } },
            { 73, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 73, DataType = SettingsDataType.Int32, Value = 0 } },
            { 74, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 74, DataType = SettingsDataType.Int32, Value = 0 } },
            { 75, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 75, DataType = SettingsDataType.Int32, Value = 0 } },
            { 76, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 76, DataType = SettingsDataType.Int32, Value = 0 } },
            { 77, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 77, DataType = SettingsDataType.Int32, Value = 0 } },
            { 78, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 78, DataType = SettingsDataType.Int32, Value = 0 } },
            { 79, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 79, DataType = SettingsDataType.Int32, Value = 0 } },
            { 80, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 80, DataType = SettingsDataType.Int32, Value = 0 } },
            { 81, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 81, DataType = SettingsDataType.Int32, Value = 0 } },
            { 82, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 82, DataType = SettingsDataType.Int32, Value = 0 } },
            { 83, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 83, DataType = SettingsDataType.Int32, Value = 0 } },
            { 84, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 84, DataType = SettingsDataType.Int32, Value = 1 } },
            { 85, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 85, DataType = SettingsDataType.Int32, Value = 0 } },
            { 86, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 86, DataType = SettingsDataType.Int32, Value = -1 } },
            { 87, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 87, DataType = SettingsDataType.Int32, Value = 0 } },
            { 88, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 88, DataType = SettingsDataType.Int32, Value = 0 } },
            { 89, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 89, DataType = SettingsDataType.Int32, Value = 0 } },
            { 90, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 90, DataType = SettingsDataType.Int32, Value = 0 } },
            { 91, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 91, DataType = SettingsDataType.Int32, Value = 0 } },
            { 93, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 93, DataType = SettingsDataType.Int32, Value = 0 } },
            { 300, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 300, DataType = SettingsDataType.Int32, Value = 0 } },
            { 104, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 104, DataType = SettingsDataType.Int32, Value = 1 } },
            { 315, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 315, DataType = SettingsDataType.Int32, Value = 0 } },
            { 316, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 316, DataType = SettingsDataType.Int32, Value = 0 } },
            { 95, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 95, DataType = SettingsDataType.Int32, Value = 1 } },
            { 96, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 96, DataType = SettingsDataType.Int32, Value = 0 } },
            { 97, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 97, DataType = SettingsDataType.Int32, Value = 0 } },
            { 295, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 295, DataType = SettingsDataType.Int32, Value = 10 } },
            { 330, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 330, DataType = SettingsDataType.Int32, Value = 0 } },
            { 331, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 331, DataType = SettingsDataType.Int32, Value = 0 } },
            { 332, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 332, DataType = SettingsDataType.Int32, Value = 0 } },
            { 333, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 333, DataType = SettingsDataType.Int32, Value = 0 } },
            { 334, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 334, DataType = SettingsDataType.Int32, Value = 0 } },
            { 140, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 140, DataType = SettingsDataType.Int32, Value = 0 } },
            { 141, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 141, DataType = SettingsDataType.Int32, Value = 0 } },
            { 142, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 142, DataType = SettingsDataType.Int32, Value = 0 } },
            { 143, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 143, DataType = SettingsDataType.Int32, Value = 0 } },
            { 98, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 98, DataType = SettingsDataType.Int32, Value = -1 } },
            { 99, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 99, DataType = SettingsDataType.Int32, Value = 0 } },
            { 130, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 130, DataType = SettingsDataType.Int32, Value = 6 } },
            { 335, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 335, DataType = SettingsDataType.Int32, Value = 0 } },
            { 336, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 336, DataType = SettingsDataType.Int32, Value = 0 } },
            { 337, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 337, DataType = SettingsDataType.Int32, Value = 0 } },
            { 338, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 338, DataType = SettingsDataType.Int32, Value = 0 } },
            { 339, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 339, DataType = SettingsDataType.Int32, Value = 0 } },
            { 340, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 340, DataType = SettingsDataType.Int32, Value = 0 } },
            { 341, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 341, DataType = SettingsDataType.Int32, Value = 0 } },
            { 342, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 342, DataType = SettingsDataType.Int32, Value = 0 } },
            { 343, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 343, DataType = SettingsDataType.Int32, Value = 0 } },
            { 344, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 344, DataType = SettingsDataType.Int32, Value = 0 } },
            { 345, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 345, DataType = SettingsDataType.Float, Value = 1065353216 } },
            { 92, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 92, DataType = SettingsDataType.Int32, Value = 0 } },
            { 350, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 350, DataType = SettingsDataType.Int32, Value = 0 } },
            { 351, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 351, DataType = SettingsDataType.Int32, Value = 0 } },
            { 317, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 317, DataType = SettingsDataType.Int32, Value = 0 } },
            { 318, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 318, DataType = SettingsDataType.Int32, Value = 0 } },
            { 319, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 319, DataType = SettingsDataType.Int32, Value = 0 } },
            { 320, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 320, DataType = SettingsDataType.Int32, Value = 0 } },
            { 106, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 106, DataType = SettingsDataType.Int32, Value = 0 } },
            { 107, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 107, DataType = SettingsDataType.Int32, Value = 0 } },
            { 108, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 108, DataType = SettingsDataType.Int32, Value = 0 } },
            { 109, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 109, DataType = SettingsDataType.Int32, Value = 0 } },
            { 110, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 110, DataType = SettingsDataType.Int32, Value = 0 } },
            { 364, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 364, DataType = SettingsDataType.Int32, Value = 0 } },
            { 365, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 365, DataType = SettingsDataType.Int32, Value = 0 } },
            { 268, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 268, DataType = SettingsDataType.Int32, Value = 1 } },
            { 269, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 269, DataType = SettingsDataType.Int32, Value = 0 } },
            { 370, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 370, DataType = SettingsDataType.Int32, Value = 0 } },
            { 371, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 371, DataType = SettingsDataType.Int32, Value = 0 } },
            { 372, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 372, DataType = SettingsDataType.Int32, Value = 0 } },
            { 373, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 373, DataType = SettingsDataType.Int32, Value = 0 } },
            { 374, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 374, DataType = SettingsDataType.Int32, Value = 0 } },
            { 375, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 375, DataType = SettingsDataType.Int32, Value = 1 } },
            { 376, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 376, DataType = SettingsDataType.Int32, Value = 0 } },
            { 377, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 377, DataType = SettingsDataType.Int32, Value = 0 } },
            { 378, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 378, DataType = SettingsDataType.Int32, Value = 0 } },
            { 379, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 379, DataType = SettingsDataType.Int32, Value = 0 } },
            { 380, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 380, DataType = SettingsDataType.Int32, Value = 0 } },
            { 310, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 310, DataType = SettingsDataType.Int32, Value = 0 } },
            { 311, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 311, DataType = SettingsDataType.Int32, Value = 0 } },
            { 312, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 312, DataType = SettingsDataType.Int32, Value = 0 } },
            { 327, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 327, DataType = SettingsDataType.Int32, Value = 0 } },
            { 313, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 313, DataType = SettingsDataType.Int32, Value = 0 } },
            { 314, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 314, DataType = SettingsDataType.Int32, Value = 0 } },
            { 383, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 383, DataType = SettingsDataType.Int32, Value = 0 } },
            { 384, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 384, DataType = SettingsDataType.Int32, Value = 0 } },
            { 385, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 385, DataType = SettingsDataType.Int32, Value = 0 } },
            { 386, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 386, DataType = SettingsDataType.Int32, Value = 0 } },
            { 392, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 392, DataType = SettingsDataType.Int32, Value = 0 } },
            { 389, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 389, DataType = SettingsDataType.Int32, Value = 0 } },
            { 387, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 387, DataType = SettingsDataType.Int32, Value = 0 } },
            { 393, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 393, DataType = SettingsDataType.Int32, Value = 0 } },
            { 395, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 395, DataType = SettingsDataType.Int32, Value = 0 } },
            { 394, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 394, DataType = SettingsDataType.Int32, Value = 0 } },
            { 366, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 366, DataType = SettingsDataType.Int32, Value = 0 } },
            { 367, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 367, DataType = SettingsDataType.Int32, Value = 0 } },
            { 368, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 368, DataType = SettingsDataType.Float, Value = 1061997773 } },
            { 226, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 226, DataType = SettingsDataType.Int32, Value = 2 } },
            { 396, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 396, DataType = SettingsDataType.Int32, Value = -1 } },
            { 127, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 127, DataType = SettingsDataType.Int32, Value = 0 } },
            { 321, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 321, DataType = SettingsDataType.Int32, Value = 0 } },
            { 322, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 322, DataType = SettingsDataType.Int32, Value = 0 } },
            { 323, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 323, DataType = SettingsDataType.Int32, Value = 0 } },
            { 324, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 324, DataType = SettingsDataType.Int32, Value = 0 } },
            { 325, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 325, DataType = SettingsDataType.Int32, Value = 0 } },
            { 326, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 326, DataType = SettingsDataType.Int32, Value = 0 } },
            { 111, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 111, DataType = SettingsDataType.Int32, Value = -1 } },
            { 397, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 397, DataType = SettingsDataType.Int32, Value = 0 } },
            { 398, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 398, DataType = SettingsDataType.Int32, Value = 0 } },
            { 399, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 399, DataType = SettingsDataType.Int32, Value = 0 } },
            { 400, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 400, DataType = SettingsDataType.Int32, Value = 0 } },
            { 401, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 401, DataType = SettingsDataType.Int32, Value = 0 } },
            { 402, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 402, DataType = SettingsDataType.Int32, Value = 0 } },
            { 292, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 292, DataType = SettingsDataType.Int32, Value = 0 } },
            { 293, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 293, DataType = SettingsDataType.Int32, Value = 3 } },
            { 294, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 294, DataType = SettingsDataType.Int32, Value = 5 } },
            { 128, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 128, DataType = SettingsDataType.Int32, Value = 0 } },
            { 112, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 112, DataType = SettingsDataType.Int32, Value = 1 } },
            { 113, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 113, DataType = SettingsDataType.Float, Value = 1056964608 } },
            { 405, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 405, DataType = SettingsDataType.Int32, Value = 0 } },
            { 406, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 406, DataType = SettingsDataType.Int32, Value = 0 } },
            { 407, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 407, DataType = SettingsDataType.Int32, Value = 0 } },
            { 408, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 408, DataType = SettingsDataType.Int32, Value = 0 } },
            { 309, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 309, DataType = SettingsDataType.Int32, Value = 0 } },
            { 409, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 409, DataType = SettingsDataType.Int32, Value = 0 } },
            { 410, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 410, DataType = SettingsDataType.Int32, Value = 0 } },
            { 411, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 411, DataType = SettingsDataType.Int32, Value = 0 } },
            { 412, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 412, DataType = SettingsDataType.Int32, Value = 0 } },
            { 413, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 413, DataType = SettingsDataType.Int32, Value = 0 } },
            { 414, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 414, DataType = SettingsDataType.Int32, Value = 0 } },
            { 415, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 415, DataType = SettingsDataType.Int32, Value = 0 } },
            { 416, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 416, DataType = SettingsDataType.Int32, Value = 0 } },
            { 417, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 417, DataType = SettingsDataType.Int32, Value = 0 } },
            { 418, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 418, DataType = SettingsDataType.Int32, Value = 0 } },
            { 419, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 419, DataType = SettingsDataType.Int32, Value = 0 } },
            { 420, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 420, DataType = SettingsDataType.Int32, Value = 0 } },
            { 421, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 421, DataType = SettingsDataType.Int32, Value = 0 } },
            { 422, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 422, DataType = SettingsDataType.Int32, Value = 0 } },
            { 423, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 423, DataType = SettingsDataType.Int32, Value = 0 } },
            { 424, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 424, DataType = SettingsDataType.Int32, Value = 0 } },
            { 425, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 425, DataType = SettingsDataType.Int32, Value = 0 } },
            { 426, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 426, DataType = SettingsDataType.Int32, Value = 3 } },
            { 427, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 427, DataType = SettingsDataType.Blob, Value = 0 } },
            { 428, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 428, DataType = SettingsDataType.Int32, Value = 0 } },
            { 429, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 429, DataType = SettingsDataType.Int32, Value = 0 } },
            { 328, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 328, DataType = SettingsDataType.Int32, Value = 0 } },
            { 431, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 431, DataType = SettingsDataType.Int32, Value = 0 } },
            { 430, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 430, DataType = SettingsDataType.Int32, Value = 0 } },
            { 432, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 432, DataType = SettingsDataType.Int32, Value = -1 } },
            { 433, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 433, DataType = SettingsDataType.Int32, Value = -1 } },
            { 434, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 434, DataType = SettingsDataType.Int32, Value = -1 } },
            { 435, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 435, DataType = SettingsDataType.Int32, Value = -1 } },
            { 436, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 436, DataType = SettingsDataType.Int32, Value = -1 } },
            { 437, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 437, DataType = SettingsDataType.Int32, Value = -1 } },
            { 438, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 438, DataType = SettingsDataType.Int32, Value = -1 } },
            { 439, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 439, DataType = SettingsDataType.Int32, Value = -1 } },
            { 440, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 440, DataType = SettingsDataType.Int32, Value = -1 } },
            { 441, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 441, DataType = SettingsDataType.Int32, Value = -1 } },
            { 442, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 442, DataType = SettingsDataType.Int32, Value = -1 } },
            { 443, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 443, DataType = SettingsDataType.Int32, Value = -1 } },
            { 444, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 444, DataType = SettingsDataType.Int32, Value = -1 } },
            { 445, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 445, DataType = SettingsDataType.Int32, Value = -1 } },
            { 446, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 446, DataType = SettingsDataType.Int32, Value = -1 } },
            { 447, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 447, DataType = SettingsDataType.Int32, Value = -1 } },
            { 448, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 448, DataType = SettingsDataType.Int32, Value = -1 } },
            { 114, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 114, DataType = SettingsDataType.Int32, Value = 0 } },
            { 449, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 449, DataType = SettingsDataType.Int32, Value = 0 } },
            { 450, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 450, DataType = SettingsDataType.Int32, Value = 0 } },
            { 451, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 451, DataType = SettingsDataType.Int32, Value = 0 } },
            { 452, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 452, DataType = SettingsDataType.Int32, Value = 0 } },
            { 460, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 460, DataType = SettingsDataType.Int32, Value = 0 } },
            { 461, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 461, DataType = SettingsDataType.Int32, Value = 0 } },
            { 462, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 462, DataType = SettingsDataType.Int32, Value = 0 } },
            { 463, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 463, DataType = SettingsDataType.Int32, Value = 0 } },
            { 464, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 464, DataType = SettingsDataType.Int32, Value = 0 } },
            { 465, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 465, DataType = SettingsDataType.Int32, Value = 0 } },
            { 466, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 466, DataType = SettingsDataType.Int32, Value = 0 } },
            { 115, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 115, DataType = SettingsDataType.Int32, Value = 1 } },
            { 453, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 453, DataType = SettingsDataType.Int32, Value = -1 } },
            { 454, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 454, DataType = SettingsDataType.Int32, Value = -1 } },
            { 105, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 105, DataType = SettingsDataType.Int32, Value = 0 } },
            { 468, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 468, DataType = SettingsDataType.Int32, Value = 0 } },
            { 469, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 469, DataType = SettingsDataType.Int32, Value = 0 } },
            { 470, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 470, DataType = SettingsDataType.Int32, Value = 0 } },
            { 471, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 471, DataType = SettingsDataType.Int32, Value = 0 } },
            { 116, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 116, DataType = SettingsDataType.Int32, Value = 0 } },
            { 346, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 346, DataType = SettingsDataType.Int32, Value = 0 } },
            { 347, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 347, DataType = SettingsDataType.Int32, Value = 0 } },
            { 348, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 348, DataType = SettingsDataType.Int32, Value = 0 } },
            { 472, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 472, DataType = SettingsDataType.Int32, Value = 0 } },
            { 473, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 473, DataType = SettingsDataType.Int32, Value = 0 } },
            { 474, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 474, DataType = SettingsDataType.Int32, Value = 0 } },
            { 475, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 475, DataType = SettingsDataType.Int32, Value = 0 } },
            { 476, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 476, DataType = SettingsDataType.Int32, Value = 0 } },
            { 477, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 477, DataType = SettingsDataType.Int32, Value = 0 } },
            { 478, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 478, DataType = SettingsDataType.Int32, Value = 0 } },
            { 481, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 481, DataType = SettingsDataType.Int32, Value = 0 } },
            { 482, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 482, DataType = SettingsDataType.Blob, Value = 0 } },
            { 483, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 483, DataType = SettingsDataType.Blob, Value = 0 } },
            { 484, new Map { Owner = OnlineProfilePropertyOwner.Game, ID = 484, DataType = SettingsDataType.Blob, Value = 0 } }
        };*/
    }
}
